# Generated by Django 5.2.5 on 2025-08-27 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        choices=[
                            ('FOSSIL', 'Fóssil'),
                            ('ARTISANSHIP', 'Artesanato'),
                            ('MINERAL', 'Mineral'),
                            ('OTHER', 'Outro'),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'tipo',
                    models.CharField(
                        choices=[('E', 'Entrada'), ('S', 'Saída'), ('A', 'Ajuste')],
                        max_length=1,
                    ),
                ),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True)),
                (
                    'endereco_estoque',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                (
                    'cost_price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'profit_margin',
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    'sale_price',
                    models.DecimalField(decimal_places=2, editable=False, max_digits=10),
                ),
                (
                    'quantity',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'unit_of_measure',
                    models.CharField(
                        choices=[
                            ('UNIT', 'Unidade'),
                            ('KG', 'Quilograma'),
                            ('LT', 'Litro'),
                            ('MT', 'Metro'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('FOSSIL', 'Fóssil'),
                            ('ARTISANSHIP', 'Artesanato'),
                            ('MINERAL', 'Mineral'),
                            ('OTHER', 'Outro'),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ('supplier', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                (
                    'minimum_quantity',
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'image',
                    models.ImageField(blank=True, null=True, upload_to='products/'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'stock_location',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
