# Generated by Django 5.2.5 on 2025-08-28 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovimentacaoEstoque',
            new_name='StockMovement',
        ),
    ]
