from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        # Renomeia os modelos (tabelas)
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Venda',
            new_name='Sale',
        ),
        migrations.RenameModel(
            old_name='ItemVenda',
            new_name='SaleItem',
        ),
        # Renomeia os campos dentro dos modelos
        migrations.RenameField(
            model_name='customer',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='documento',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='tipo',
            new_name='customer_type',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='telefone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='data_cadastro',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='observacoes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='cliente',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='data_venda',
            new_name='sale_date',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='forma_pagamento',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='desconto',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='observacoes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='custo_total',
            new_name='total_cost',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='venda',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='produto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='quantidade',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='preco_unitario',
            new_name='unit_price',
        ),
    ]