# Generated by Django 5.2.5 on 2025-09-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='saldo',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(
                choices=[
                    ('ADMIN', 'Administrador'),
                    ('SELLER', 'Vendedor'),
                    ('STOCKCLERK', 'Estoquista'),
                ],
                default='SELLER',
                max_length=10,
            ),
        ),
    ]
