# Generated by Django 5.2.5 on 2026-04-27 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCostEntry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('RENT', 'Aluguel'),
                            ('WATER', 'Água'),
                            ('ELECTRICITY', 'Luz'),
                            ('INTERNET', 'Internet'),
                            ('SALARIES', 'Salários de Funcionários'),
                            ('TAXES', 'Taxas'),
                            ('OPERATIONAL', 'Despesas Operacionais'),
                            ('MAINTENANCE', 'Manutenção'),
                        ],
                        max_length=20,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=255)),
                (
                    'value',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ('due_date', models.DateField()),
                (
                    'paid_at',
                    models.DateField(
                        blank=True,
                        help_text='Date the entry was actually paid. Set automatically on status change.',
                        null=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('PENDING', 'Pendente'), ('PAID', 'Pago')],
                        default='PENDING',
                        max_length=10,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_updated',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Custo Fixo',
                'verbose_name_plural': 'Custos Fixos',
                'ordering': ['due_date'],
            },
        ),
    ]
